### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by jsaucerman** [saucermanlab/SarcOrgTextureAnalysis#1]
A potential bug was reported by Jereon Stein:
![image](https://user-images.githubusercontent.com/13834906/154506533-a314ccf3-b3e4-4a30-9158-14ac4cf64082.png)

This has not been verified.  It appears it's in the plotting of the results, not the actual algorithm. And related to the struct eCM. I wonder if there was a MATLAB version issue for how structs are handled?

**Comment by dtf5cg** [comment]
I had the same bug. 

I was able to fix by changing line 20 to
> eCM_images = dir(fullfile(eCM_imageSourceFolder, '*C1.tif'));

and I changed folder locations to have a forward-slash

> eCM_imageSourceFolder = './Images/Endogenous CM/';
> eCM_imageWriteFolder = './Images/Endogenous CM Segmented/';

You can see that the image files now get imported correctly using `nfiles = length(eCM_images);`

**Comment by dtf5cg** [comment]
P.S. If you see this hi Dr. Saucerman! :) @jsaucerman Looking forward to trying out this code on my images.

**Comment by jsaucerman** [comment]
It's so great to hear from you! Will send an email, and will try to incorporate your fixes so they can help others.

**Comment by jsaucerman** [comment]
I've incorporated the code edits from @dtf5cg, thanks so much! 

I've noticed that the "Dot indexing is not supported" can happen if it doesn't see any images. Download the example images first. We could add better error handling.
